# Generated by Django 5.1.2 on 2024-12-22 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transpose_value', models.IntegerField(default=0)),
                ('font_size', models.CharField(default='14px', max_length=5)),
                ('line_spacing', models.FloatField(default=1.2)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('chord_color', models.CharField(default='#FF0000', max_length=7)),
                ('chord_weight', models.CharField(default='normal', max_length=10)),
                ('instrument', models.CharField(default='guitar', max_length=20)),
                ('is_lefty', models.BooleanField(default=False)),
                ('chord_diagram_position', models.CharField(default='bottom', max_length=10)),
                ('chord_placement', models.CharField(default='inline', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
