# Generated by Django 5.1.2 on 2024-12-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='instrument',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('ukulele', 'Ukulele'), ('baritone_ukulele', 'Baritone Ukulele'), ('banjo', 'Banjo'), ('mandolin', 'Mandolin')], default='ukulele', max_length=20),
        ),
    ]
