# Generated by Django 5.1.4 on 2025-02-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpreference_is_printing_alternate_chord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='instrument',
            new_name='primary_instrument',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='secondary_instrument',
            field=models.CharField(blank=True, choices=[('guitar', 'Guitar'), ('ukulele', 'Ukulele'), ('baritone_ukulele', 'Baritone Ukulele'), ('banjo', 'Banjo'), ('mandolin', 'Mandolin')], max_length=20, null=True),
        ),
    ]
