# Generated by Django 5.1.4 on 2025-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_primary_instrument_userpreference_instrument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='instrument',
            new_name='primary_instrument',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='chord_color',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='chord_diagram_position',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='chord_placement',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='chord_weight',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='line_spacing',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='text_color',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='secondary_instrument',
            field=models.CharField(blank=True, choices=[('guitar', 'Guitar'), ('ukulele', 'Ukulele'), ('baritone_ukulele', 'Baritone Ukulele'), ('banjo', 'Banjo'), ('mandolin', 'Mandolin')], default=None, max_length=20, null=True),
        ),
    ]
