# Generated by Django 5.1.2 on 2024-11-01 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0003_alter_song_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('chords_and_lyrics', models.JSONField(blank=True, null=True)),
                ('last_parsed', models.DateTimeField(auto_now=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='songbook.song')),
            ],
        ),
    ]
