# Generated by Django 5.1.2 on 2024-11-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0004_parsedsong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParsedSong',
        ),
    ]
