# Generated by Django 5.1.2 on 2024-11-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0005_delete_parsedsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
