# Generated by Django 5.1.2 on 2024-11-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0006_song_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_with_chords',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
