# Generated by Django 5.1.2 on 2024-11-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0008_alter_song_lyrics_with_chords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics_with_chords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
