# Generated by Django 5.1.2 on 2024-11-10 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0009_alter_song_lyrics_with_chords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tuning', models.JSONField()),
                ('alternate_names', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('positions', models.JSONField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbook.instrument')),
            ],
        ),
    ]
