# Generated by Django 5.1.2 on 2024-12-18 11:24

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0010_instrument_chord'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Chord',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
