# Generated by Django 5.1.2 on 2024-12-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0012_alter_song_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='abc_notation',
            field=models.TextField(blank=True, help_text='Optional ABC notation for this song.', null=True),
        ),
    ]
