# Generated by Django 5.1.4 on 2025-01-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0013_song_abc_notation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='abc_notation',
        ),
    ]
