# Generated by Django 5.1.4 on 2025-02-01 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0014_remove_song_abc_notation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.JSONField(blank=True, default=dict)),
                ('verse', models.JSONField(blank=True, default=dict)),
                ('chorus', models.JSONField(blank=True, default=dict)),
                ('bridge', models.JSONField(blank=True, default=dict)),
                ('interlude', models.JSONField(blank=True, default=dict)),
                ('outro', models.JSONField(blank=True, default=dict)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songbook.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
    ]
