# Generated by Django 5.1.4 on 2025-02-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0015_songformatting'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='acknowledgement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
