# Generated by Django 5.1.4 on 2025-02-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0016_song_acknowledgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songTitle',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
