# Generated by Django 5.1.4 on 2025-03-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0017_alter_song_songtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='site_name',
            field=models.CharField(choices=[('FrancoUke', 'FrancoUke'), ('StrumSphere', 'StrumSphere')], default='FrancoUke', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='songTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
